# Generated by Django 3.1.1 on 2020-09-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_thingtodo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodo',
            name='is_default_project',
            field=models.BooleanField(default=False),
        ),
    ]
