# Generated by Django 3.1.1 on 2020-09-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200924_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttodo',
            name='is_default_project',
        ),
        migrations.AlterField(
            model_name='thingtodo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo.projecttodo'),
        ),
    ]
