# Generated by Django 3.1.2 on 2020-10-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingtodo',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
