# Generated by Django 3.1.2 on 2020-10-10 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201010_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingtodo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
